### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by 1div0** [eteran/nedit-ng#83] opened 2019-01-10 15:53 UTC
Please evaluate and consider adding support of Unicode based upon the XNEdit https://github.com/unixwork/xnedit

**Comment by eteran** [comment] 2019-01-10 23:50
closing because this is a duplicate of issue #31 ... but **thank you** for finding example code that I can use as a jumping off point!

**Closed by eteran** 2019-01-10 23:50 UTC
