### ISSUE TITLE
several dialogs should be non modal

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#264] opened 2021-01-11 01:38 UTC
Found a few dialogs that have been made modal:

- [x] Language Modes
- [x] Text Drawing Styles
- [x] Syntax Highlighting Patterns
- [x] Colors
- [x] Customize Window Title
- [x] Text Font

There should be non-modal per original nedit

**Comment by eteran** [comment] 2021-01-11 03:36
I agree. During porting, it was easier to guarantee correctness if things were made modal, but I think it is better to preserve the original modality.

**Comment by eteran** [comment] 2021-01-11 03:40
This is a partial duplicate of issue #120 but is more comprehensive than that one. So I'm going to close THAT one in favor of this one since this one lists all the dialogs that need addressing.

**Comment by tksoh** [comment] 2021-01-11 04:13
there were some issue when I tried to create a new lang mode for cmake using NG, but this issue is making a bit harder to let me proceed, so I will revisit that issue when this one is closed.

Meanwhile, I will use nedit 5 to work on the cmake lang mode.

**Comment by eteran** [comment] 2021-01-11 04:23
The issue being that you couldn't see updates in real-time due to it being modal? Or something different as well?

**Comment by tksoh** [comment] 2021-01-11 04:30
I can't be sure right now, but it feels more like sometimes the patterns either didn't capture the text as expected, or not applying the style correctly.

**Comment by eteran** [comment] 2021-01-11 05:09
Hmm, if that's the case, that would be an issue with either the syntax highlighter algorithm or the regex engine.

I'm not aware of any specific bugs in those, but certainly, report them if you encounter any!

**Comment by eteran** [comment] 2021-01-11 20:32
1 down :-)

**Comment by eteran** [comment] 2021-01-11 20:41
So looking into this, the non-modality does have some questionable behavior in some specific corner cases.

Specifically, a few dialogs serve dual roles, for example, the Text Fonts dialog. It can be shown either because the user wants to edit global settings, or because they want to edit the settings for the current document.

Where it gets weird is that these are technically the same dialog, just constructed with different parameters. So if a user opens the "Default Preferences" version and then for some reason tries to open the Text Fonts for the current dialog, the result is that the focus is simply shifted to the Default Preferences version. If they edit it there, they aren't editing the per-document settings at all (same vice versa).

Also, in NEdit5, I can trivially instigate a crash by opening any document-specific non-modal dialog, closing the document it's opened for, and then clicking OK in the dialog. (For example, create two tabs, Preferences -> Text Fonts, click the close tab button, click apply in the Text Fonts dialog... boom).

These concerns can of course be dealt with (the second one should be pretty trivial). But it is simply not something that even needs addressing with modal dialogs.

**Comment by eteran** [comment] 2021-01-11 20:44
I'm also not a huge fan of the fact that if you have two or more full windows open, you can (even in NEdit5) open multiple of nearly any given non-modal dialog since they are "TopLevelWindow" specific, not application-specific. But that's a different issue altogether and is one that NG reluctantly replicates in some places.

**Comment by grege2** [comment] 2021-01-11 22:13
"in NEdit5, I can trivially instigate a crash ..."  I checked this on Nedit5-X11 on Mac Mojave, and yes closing the tab, then hitting Ok in the Font Dialog, crashes nedit. 

This is the canonical hazard of non-modal dialogs, and definitely Motif. It was exhaustively worked on by Doug Young in his book 
https://www.amazon.com/Object-Oriented-Programming-OSF-Motif/dp/0132092557

He surrounded all Motif widgets with a C++ class which ensured that you could not reference a widget that been destroyed by some other thread. It was painfully laborious to code with though. And it's all history now.

I think one should go slowly in opening up modal dialogs to be non-modal, much as it's annoying at times. They might be non-modal and reasonably safe in Nedit5-X11, but that is in the context of a completely different Gui package and windowing system. There might be actions that the user can take in Qt, with multiple windows, tabs, screens in use, on Linux, Windows, Mac, that open up a hazard. It could be a lot of testing to check it all. But Qt could already have safeguards against crashes like the above, ie. referencing a destroyed widget or resource. But, it could still corrupt other data maybe. 

Anyway, I would go somewhat carefully. Ciao.

**Comment by eteran** [comment] 2021-01-11 23:24
Fortunately, Qt has a nice solution to this. Qt offers what I'd call "almost smart pointers" :-P.

Basically, if I use a `QPointer<Dialog> dialog;` it acts just like an ordinary pointer, with no reference counting, or lifetime control. What it does offer is that is it automatically set to `nullptr` if the object it points to is deleted, even if elsewhere in the code.

So, if done thoughtfully, this tool can be used to allow dialogs to have weak references to documents, and also be passively aware if the document it refers to is deleted.

**Comment by grege2** [comment] 2021-01-11 23:35
Aha, I wondered if Qt had something like that, excellent. Well that piece of the puzzle seems covered.

**Comment by tksoh** [comment] 2021-01-12 01:38
> Also, in NEdit5, I can trivially instigate a crash by opening any document-specific non-modal dialog, closing the document it's opened for, and then clicking OK in the dialog. (For example, create two tabs, Preferences -> Text Fonts, click the close tab button, click apply in the Text Fonts dialog... boom).

It's a miracle that nedit was able to survive through those years without this becoming a problem ;-)

Sounds like QPointer could be the answer. Hopefully it doesn't that too much trouble to implement.

**Comment by eteran** [comment] 2021-01-12 02:09
> It's a miracle that nedit was able to survive through those years without this becoming a problem ;-)

Ha! I of course recognize a trivial problem when I see it. But I'm also the type who strives for perfection as much as I can. So in my mind if it can be made to crash, it NEEDS to be fixed 🙂

**Comment by anjohnson** [comment] 2021-01-12 02:18
> I'm also the type who strives for perfection as much as I can. So in my mind if it can be made to crash, it NEEDS to be fixed 🙂

One of the reasons I've been contributing as much as I have, it's easy to get you to fix stuff that isn't working quite right... 😉

**Comment by tksoh** [comment] 2021-01-12 02:34
> Ha! I of course recognize a trivial problem when I see it. But I'm also the type who strives for perfection as much as I can. So in my mind if it can be made to crash, it NEEDS to be fixed 🙂

That I'd consider a virtue :-)

**Comment by tksoh** [comment] 2021-01-12 08:56
@eteran BTW, any chance to fix the highlight pattern dialog quickly. Just to make it easier for me to continue my work on the new lang modes?

**Comment by eteran** [comment] 2021-01-12 13:05
I'll do that one next 🙂

**Comment by eteran** [comment] 2021-01-13 05:44
@tksoh Syntax dialog should be non-modal now :-)

**Comment by eteran** [comment] 2021-01-15 04:54
Text Drawing Styles is done. Half way there :-)

**Closed** 2022-04-02 15:04 UTC
