### ISSUE TITLE
auto scroll preference has no effect

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#296] opened 2021-01-28 09:01 UTC
Using commit 959597a9c1bf2ad07aae3ec34667b0f6b2f82dca

With the preference enabled, NG does not automatically scroll the lines up/down according to the padding value, even though we have not reached the start/end of the file:

> nedit.autoScroll=true
> nedit.autoScrollVPadding=4

**Comment by eteran** [comment] 2021-01-28 15:47
Hmm, I'm pretty sure that this logic was not removed in the port, so I'll have to see what the difference in behavior is.

Is it basically that (given the above settings), we should expect it to scroll if the cursor is within 4 lines of the top/bottom?

**Comment by tksoh** [comment] 2021-01-29 01:02
that's what the doc says, and apparently how it works in nedit 5.

> When this option is enabled the window will automatically scroll when the cursor comes 4 lines from the top or bottom of the window (except at the beginning of the file). The number of lines can be customized with the nedit.autoScrollVPadding setting in the config.ini file.

**Comment by eteran** [comment] 2021-01-29 02:51
Van we confirm that NEdit5 behaves as expected? Just to be sure?

**Comment by tksoh** [comment] 2021-01-29 02:54
I have confirmed it, naturally. Else I wouldn't have known it doesn't work on NG 😅

**Comment by eteran** [comment] 2021-01-29 03:02
Fair enough 😜, I'll try to reproduce locally and go from there.

**Comment by eteran** [comment] 2021-01-29 03:04
I can say that the version of NG that will tender a partial line may just simply not handle this right because that build just simply pretends that there is one extra line.

I think you are using that one, so just as a heads up, I'll be trying to reproduce this on the current master.

**Comment by tksoh** [comment] 2021-01-29 03:12
I tried commit 9e9acf13b028d86a5a9951b3534a5a71bcad6d7c, and it has the same problem

**Comment by eteran** [comment] 2021-01-29 03:46
@tksoh Confirmed.

For some reason, the `dragState_` is not being reset, which effectively perminantly disables the feature. Looking into it.

**Comment by eteran** [comment] 2021-01-29 03:52
I believe it should be fixed in master now. Accidentally had inverted a single condition. Once restored, appears to work the same as NEdit5 as far as I can tell.

Please re-open if the issue is still present :-)

**Closed by eteran** 2021-01-29 03:52 UTC
