### ISSUE TITLE
macOS build issues

### ISSUE THREAD

**Issue by rnmhaddad** [eteran/nedit-ng#127] opened 2019-09-04 04:24 UTC
Code fails to compile on macOS:
1. missing header
2. X11 library path (-L missing)

**Comment by rnmhaddad** [comment] 2019-09-04 04:32
can I contribute fixes to this project?

**Comment by eteran** [comment] 2019-09-04 14:32
Thanks!

**Comment by anjohnson** [comment] 2019-11-19 18:16
Replying to this issue since this is an update: To get my build of 2019.4 to succeed on macOS Mojave (10.14.6) I had to change the `link_directories` paths to be `/opt/X11/lib` and in src/TextArea.cpp remove the `#ifdef Q_OS_MACOS` block around lines 430-436 as the four `TextArea::*AP` symbols in that block were not defined.

**Comment by eteran** [comment] 2019-11-19 20:54
Ah, good to know. I hadn't done a macOS build in a while. Seems it got missed during some refactoring. Should be easy to fix though.

**Comment by anjohnson** [comment] 2019-11-20 04:48
Now I've actually tried to use the result on macOS I'm seeing other problems, and my fix above was wrong (I disabled my arrow keys completely). The proper fix to TextArea.cpp is just to remove the `AP` from the ends of those symbol names inside the ifdef block.

Other issues I've noticed so far:
* With the OS General Appearance set to Dark some things become invisible, such as unselected text inside most text input boxes (e.g. in the Find/Replace dialog), filenames in the File Open dialog etc. The Light appearance works fine though.
* When I open lots of tabs, the width of the window expands to hold all the tabs.
* The keyboard shortcuts shown in some menu items are mixed, some say `[Shift] Ctrl+F` whereas the more standard items use Apple's single-characters for Shift and Command (and of course the above text is wrong, the short-cut used on MacOS for Find is Command+F, not Ctrl+F).

**Comment by eteran** [comment] 2019-11-21 00:26
I'll definitely look into it. Currently macOS isn't quite a first class citizen for nedit-ng because I have a limited ability to test it. But I'll do my best.

**Comment by eteran** [comment] 2020-12-08 12:20
@anjohnson I just pushed a style setting which should hopefully address the lack of scrollable tabs. Unfortunately, the "native" style simply doesn't support it, so it will make the app look slightly less native.

**Comment by anjohnson** [comment] 2020-12-09 19:03
That does fix the problem of tabs making the window wider, thanks. I actually slightly prefer this style of tabs over the Apple's too, when there are only 2 tabs present these make it more obvious which one is active. Of course using Apple's X tab-close button would be a bit more intuitive, but that seems to be theme-specific so I'm not going to ask you to fix that.

![image](https://user-images.githubusercontent.com/5453863/101665524-b1199c00-3a12-11eb-90ec-8aa9d8a78249.png)

BTW I did notice that almost any edit to the source files now causes cmake to recompile everything (even files that I haven't changed), have you seen that? I suspect the `NEDIT_VERSION_GIT` generation is probably to blame. I'm not a cmake user so I can't suggest how to fix it here, but in my build system we put that kind of version info into a header file instead and ensure that if the file contents won't change we don't actually update the file at all.

**Comment by eteran** [comment] 2020-12-09 23:26
Ah, I'll see if I can make the GIT stuff a bit more surgical for rebuilds.

**Comment by tksoh** [comment] 2020-12-10 00:37
The NEDIT_VERSION_GIT approach was very much a hack, as I was a bit reluctant to change the structure of the source, i.e. adding the auto-generated header. Maybe that's what needs.

@anjohnson In any case, editing the source should not result in recompiling the whole tree -- this is what the make system is for after all -- unless you touch the cmake files. I don't see this issue on Windows 10 and Linux Mint. I have no idea why it would on MacOS. Can you help share the messages in Compiler Output and General Messages in Qt Creator? Also, perhaps you can try experiment by checking out and editing the version before the NEDIT_VERSION_GIT commit too.

**Comment by eteran** [comment] 2020-12-10 01:31
@tksoh I think the issue **might** be that if you edit a file, it adds "-dirty" to the define, which if you're coming from a clean source tree, means that every single file is getting a new define passed, and thus, a rebuild? Maybe?

**Comment by eteran** [comment] 2020-12-10 01:32
I think there's a better solution though, instead of a define, we can generate a version.h file (or similar), and have a minimal number of files include that one. Should mean only a few things get rebuilt.

**Comment by tksoh** [comment] 2020-12-10 02:12
The state change to dirty might potentially triggers that, but only if you reload the program, or touch the main cmake file. This is actually a bug in the -DNEDIT_VERSION_GIT approach I discovered recently, that the version info is only captured during cmake configure time, so it doesn't know when the source has been updated after the project is loaded into Qt Creator.

On the auto-generation of version.h file, I think it's a right way to go too -- my earlier approach is looking more like a cheap hack now ;-). In fact, I actually have something sitting in my local branch to do just that right now, but there's still a small issue I am investigating. 

CMake is a beast :-(

**Comment by eteran** [comment] 2020-12-10 02:12
@anjohnson OK, I implemented the version.h.in concept, and I can confirm, it does not cause a full rebuild when you have a dirty repo. So that should be fixed in master.

So on this ticket, which issue are outstanding?

Is dark mode still an issue (I long ago made dark mode friendly icons).

Keyboard shortcuts are a bit of a toughie, because Qt on macOS auto-exchanges Ctrl and Cmd implicitly for user's convenience. I can probably try to make the shortcuts use mac style shift/command/ctrl icons... but that's cosmetic.

**Comment by eteran** [comment] 2020-12-10 02:14
@tksoh I just updated master to use an include file, but you're right, it of course only captures the version at configure time. It's a limitation, but not a huge one. 99% of the time, the info there is useful for people reporting bugs so I don't need to ask "what version are you running?"

The git rev gets us that (and I added the ability to capture the git commit too, I just don't display it anywhere yet)

**Comment by tksoh** [comment] 2020-12-10 02:16
Once again, you beat me on the reply ;-)  Very quick work! I will try your change later today ^^

**Comment by eteran** [comment] 2020-12-10 02:21
@tksoh I'm just enthusiastic because adoption is finally picking up and I'm enjoying the user base growing and giving feedback :-D!

**Comment by tksoh** [comment] 2020-12-10 02:32
I know that feeling 😊

**Comment by anjohnson** [comment] 2020-12-10 17:31
Yes that fixes the rebuild issue. In our GNU-make build system we force make to always rebuild the header file (at make time, although we don't actually have a separate configure step), but then have the Perl script which actually does the work compare the existing header file with what it would write and not do anything if the content wouldn't change.

I don't have time to check the dark-mode stuff right now, I'll get back to you on that.

This is what my Edit menu looks like, to compare the short-cut text:

![image](https://user-images.githubusercontent.com/5453863/101805565-86921680-3ad8-11eb-9944-00987e716ae2.png)

I don't have a problem with it showing "Shift" instead of "⇧" or "Ctrl" instead of "⌃" since that's cosmetic, but the actual short-cuts for the Shift Left and Shift Right options use the Command key instead of Ctrl on the Mac, so the menu shown above is wrong. If the cosmetic thing matters to you, the Unicode chars they use can be found in the answers to [this stack-exchange](https://apple.stackexchange.com/questions/55727/where-can-i-find-the-unicode-symbols-for-mac-functional-keys-command-shift-e).

It would be nice if some of the basic editing short-cuts could match Apple's keys, word-left/right which I use a lot for navigation are the main ones that I have to make a mental switch between pressing ⌘ (command) and ⌥ (option/alt) for.

Thanks!

**Comment by eteran** [comment] 2020-12-10 18:32
So I do have a plan to a ".config/nedit-ng/shortcuts.yaml" file which would let users specify ALL shortcuts... eventually. But it's gonna be a big undertaking. When I'm done, I can of course have a different default version of this for mac/windows/linux/etc...

We'll get there eventually!

**Comment by tksoh** [comment] 2020-12-11 13:31
@eteran on the version info, can we add the branch name also, perhaps By appending "[branch-name]" to version string ? It would be  very helpful for those who work on multiple branches of nedit-ng.

**Comment by eteran** [comment] 2020-12-11 14:01
Sure, that should be easy

**Comment by anjohnson** [comment] 2020-12-11 20:17
Dark mode looks great now, I just have to change my color settings on that machine so the nedit-ng window doesn't stick out like a lighthouse!

**Comment by eteran** [comment] 2020-12-27 22:40
I'm going to close this issue because it spans several discussions and I think all the actual build issues have been dealt with meaning all that is left are some cosmetic things.

Please do feel free to open specific issues for any issues though if they persist so they can be tackled!

**Closed by eteran** 2020-12-27 22:40 UTC
