### ISSUE TITLE
very persistent error dialog in pattern editors

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#266] opened 2021-01-11 07:14 UTC
I have an error in my highlighting pattern, and NG prompts me with a dialog about the error when I hit 'Check'. Every time, I have to click multiple times on the OK button for the dialog to finally go away, and the number of clicks seems to be less on Linux (2x) vs Windows (4x).

![2021-01-11 15_05_07-Syntax Highlighting Patterns](https://user-images.githubusercontent.com/494222/104154092-f7518900-541e-11eb-9820-9512ba8532ec.jpg)

**Comment by eteran** [comment] 2021-01-11 14:53
OK, I'll see what I can do to make that less annoying!

**Comment by eteran** [comment] 2021-01-11 19:35
Hmm, this must be an event firing different on different platforms kinda thing. Because in KDE, I only get the message once per "Check". I'll see if I can replicate it on Ubuntu.

**Comment by eteran** [comment] 2021-01-11 19:40
Hmm, so far, can't replicate on Ubuntu+XFCE... I'll try windows when I get home from work too.

One thing that I am thinking may just circumvent this would be a small UI tweak.

We could abandon the "Check" button, and instead, just have a Red X or a Green Check next to each field that is updated as you type, and you'd only get a dialog box if you tried to click OK/Apply.

I don't know if that kinda change is too much for the 6.0 target though.

**Comment by grege2** [comment] 2021-01-11 21:14
I checked on Mac. All ok there, only one click needed on OK to dismiss dialog.
(Dialog is modal, as discussed elsewhere).

Catalina 10.15.7, nedit master of 12 jan. Nedit invoked as `nc-ng filename`, no explicit server, no multiple windows, tabs, screens, hosts. I'm afraid my environment is the canonical vanilla one.

**Comment by eteran** [comment] 2021-01-11 21:38
@grege2 Thanks for the data points :-)

**Comment by tksoh** [comment] 2021-01-12 01:08
> We could abandon the "Check" button, and instead, just have a Red X or a Green Check next to each field that is updated as you type, and you'd only get a dialog box if you tried to click OK/Apply.

I am not into changing the UI so drastically just to get around the problem, at least not for 6.0. And I suspect that change might lead to other complication eventually too. 

I haven't looked into the code to understand why 'event' is even involved here, but looks to me it's supposed to be pretty straightforward: check returns status, then prompt a dialog to show the result pass/fail. Perhaps I am underestimating the complexity of macro's architecture.

**Comment by eteran** [comment] 2021-01-12 02:28
To be honest, I'm only guessing when I bring up "events". It really should be exactly as straight forward as you describe

**Comment by eteran** [comment] 2021-01-13 05:40
@tksoh I've found that an EMPTY regex triggers the repeated message box behavior and have a fix incoming :-) It is possible that other small errors would follow the same code path. So I **think** that I may have this one squared away.

**Comment by eteran** [comment] 2021-01-13 05:47
@tksoh I think I have this fixed in master, if it appears so, I think we can close this issue :-).

**Comment by tksoh** [comment] 2021-01-13 06:43
Tested on Windows. Looks good. Thanks 👍

**Comment by tksoh** [comment] 2021-01-22 08:51
@eteran I ran into this. Using the following macro, NG would prompt the "Parse Error" dialog twice, followed by the 3rd dialog saying "Macro compiled without error"

> if (a==1) {
> 
> }
> }


With commit 455817323effad87929996262b6d0800cdfd6eda. Affects both Windows and Linux


![2021-01-22 16_49_12-Macro Commands](https://user-images.githubusercontent.com/494222/105468440-f566b000-5cd1-11eb-8359-92a35e139491.jpg)
![2021-01-22 16_48_56-MINGW64__c_Users_teeka_OneDrive_Documents_projects_nedit-ng](https://user-images.githubusercontent.com/494222/105468448-f697dd00-5cd1-11eb-9f1a-a7018eabe307.jpg)
![2021-01-22 16_49_25-Macro Commands](https://user-images.githubusercontent.com/494222/105468453-f7307380-5cd1-11eb-8429-63afb1a2d8e4.jpg)

**Comment by eteran** [comment] 2021-01-22 15:09
Confirmed, occurs when you press the Check button, additionally, hitting OK will cause one error to pop up, but then it saves the macro and closes the dialog anyway.

**Comment by eteran** [comment] 2021-01-22 15:42
Should be fixed (again), LOL. There was a code path that was reporting an error, but not returning `false`.

**Closed by eteran** 2021-01-22 15:42 UTC
