### ISSUE TITLE
characters " ' ` ~ not accessible within WSL environment

### ISSUE THREAD

**Issue by patricevenant** [eteran/nedit-ng#169] opened 2020-10-27 15:04 UTC
I can't have the characters " ' ` ~ in editor when I pressed the keyboard. With my keyboard, I need to pressed <"> + space key to got it. This working with other Qt applications but not with NEdit, I try to modify environment variables, like LANG=en. But no success :(

Have you an idea ?
Thanks

**Comment by eteran** [comment] 2020-10-29 03:45
I'll have to look into it. What X server are you using (so I can test locally)?

**Comment by patricevenant** [comment] 2020-10-29 17:52
I'm using MobaXterm (Personal Edition v20.2)

**Comment by eteran** [comment] 2020-10-30 00:38
nice, I'll check it out :-D

**Comment by eteran** [comment] 2020-12-17 02:49
So I can say that I have been unable to reproduce locally. I am using VCXSrv and set the following environment variables:

```
DISPLAY=172.28.96.1:0.0
LIBGL_ALWAYS_INDIRECT=1
```

Obviously `DISPLAY` needs to match the correct things for YOUR system  as I'm sure you already know :-)

Have you tried forcing a US keyboard layout with:

```
setxkbmap -layout us
```
?

**Comment by patricevenant** [comment] 2020-12-17 14:10
I did  `setxbmap -layout us`  That's perfect ! Thanks a lot.

**Comment by eteran** [comment] 2020-12-17 14:53
Wahoo! Closing then since it's a configuration level issue.

Please re-open if you have any other related issues.

**Closed by eteran** 2020-12-17 14:53 UTC
