### ISSUE TITLE
Snippet expansion capability (Macro reading is incorrectly sensitive to Unicode characters)

### ISSUE THREAD

**Issue by agarrubio** [eteran/nedit-ng#42] opened 2018-05-21 08:18 UTC
Nedit had this capability through the expander macro. Should it be working in nedit-ng? Is ther an alternative?

**Comment by agarrubio** [comment] 2018-05-22 01:57
The "expand" command converts "TAB"s to spaces. Unexpand does the opposite.
On the other hand, Nedit's "expander.nm" would expand "IMHO" to "In my humble opinion", and much more complex things, including "placeholders" for variables in code. Most code editors include them, and call them snippets. 
https://en.wikipedia.org/wiki/Snippet_(programming)
By the way, just yesterday I was thrilled to know that you are resurrecting Nedit: I can't thank you enough!

**Comment by eteran** [comment] 2018-05-22 03:01
expander.nm seems to be part of the nedit-macro-kit. https://github.com/mrbald/nedit-macro-kit/blob/master/macro-kit/macro/expander.nm

This should "just work" if you add those macros to nedit-ng. If it does not, please let me know what specifically is not working with it.

**Comment by agarrubio** [comment] 2018-05-22 06:04
Every day I use nedit 5.6 with an old expander I've got long time ago. 
Today I cloned https://github.com/mrbald/nedit-macro-kit.git and installed using
the macro-kit/install/nedit-5.5.rc file provided, since there is no version for 5.6.
Everything worked! 

Then, to install into nedit-ng, I altered the version of nedit-5.5.rc so that it pretends to be 5.6. Then I used "import-nedit" to import that configuration file. So far, so good! However, when I try to load the macro file "autoload.nm" (as I did in Nedit 5.6), nedit-ng crashes with "segmentation fault".

I don't want to waste your time with my problems, but if you have some quick thoughts, that would be useful.
Many thanks!

**Comment by eteran** [comment] 2018-05-22 14:38
Great, we can replicate the problem!

Can you tell me which version of nedit-ng you are using? If you aren't trying the latest master branch, please do. If you're already on master, please let me know and I'll do what I can to reproduce this locally and quickly fix it as a segfault should **never** happen.

**Comment by eteran** [comment] 2018-05-23 21:17
This patch should make the import and loading of macros from the nedit-macro-kit work correctly! Now non-english characters in the macro code won't break loading or importing.

Since that kit provides the capability requested, I'm closing this issue.

**Closed by eteran** 2018-05-23 21:17 UTC
