### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by geimer** [eteran/nedit-ng#149] opened 2020-01-12 14:51 UTC
I'm experiencing a weird font issue. When using, for example, the "DejaVu Sans Mono" font family and syntax highlighting enabled, keywords are in bold (as expected). With other fonts (e.g., "Courier", "Hack" or "Noto Mono"), however, they are not. Instead, the regular text font is used. In all cases, the corresponding font files are installed and picked up by other editors, e.g., `kate`. Also, italics (e.g., used for comments) work fine. Any idea what may be going wrong or how to debug this?

Release: 2019.4
OS: Debian 10 "buster"
Qt: 5.11.3

**Comment by eteran** [comment] 2020-01-13 13:52
Do you happen to be using KDE? There is a known bug with KDE and fonts (and has a relatively easy work around).

See https://bugs.kde.org/show_bug.cgi?id=378523

The solution is basically to open `.config/kdeglobalsrc` and remove `,Regular` from any font entries you see. Log out and log back in and then Qt apps should be able to properly request bold/italic fonts reliably.

Let me know if that solves the issues for you.

**Comment by geimer** [comment] 2020-01-13 14:35
Yes, I'm using KDE.  However, there are no font entries in my `.config/kdeglobals`...

**Comment by eteran** [comment] 2020-01-13 15:19
Just to satisfy my curiosity... could you attach your `.config/kdeglobals` file? Mine definitely has several font entries scattered throughout it.

**Comment by geimer** [comment] 2020-01-13 15:56
The system has been set up just recently and I haven't tinkered with the global font settings yet. That may explain why I don't have such entries. But anyway, here you go:
```
[$Version]
update_info=filepicker.upd:filepicker-remove-old-previews-entry,fonts_global.upd:Fonts_Global,fonts_global_toolbar.upd:Fonts_Global_Toolbar

[ColorEffects:Disabled]
ChangeSelectionColor=
Color=56,56,56
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
Enable=
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color=112,111,110
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=77,77,77
BackgroundNormal=49,54,59
DecorationFocus=61,174,233
DecorationHover=61,174,233
ForegroundActive=61,174,233
ForegroundInactive=189,195,199
ForegroundLink=41,128,185
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=239,240,241
ForegroundPositive=39,174,96
ForegroundVisited=127,140,141

[Colors:Complementary]
BackgroundAlternate=59,64,69
BackgroundNormal=49,54,59
DecorationFocus=30,146,255
DecorationHover=61,174,230
ForegroundActive=246,116,0
ForegroundInactive=175,176,179
ForegroundLink=61,174,230
ForegroundNegative=237,21,21
ForegroundNeutral=201,206,59
ForegroundNormal=239,240,241
ForegroundPositive=17,209,22
ForegroundVisited=61,174,230

[Colors:Selection]
BackgroundAlternate=29,153,243
BackgroundNormal=61,174,233
DecorationFocus=61,174,233
DecorationHover=61,174,233
ForegroundActive=252,252,252
ForegroundInactive=239,240,241
ForegroundLink=253,188,75
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=239,240,241
ForegroundPositive=39,174,96
ForegroundVisited=189,195,199

[Colors:Tooltip]
BackgroundAlternate=77,77,77
BackgroundNormal=49,54,59
DecorationFocus=61,174,233
DecorationHover=61,174,233
ForegroundActive=61,174,233
ForegroundInactive=189,195,199
ForegroundLink=41,128,185
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=239,240,241
ForegroundPositive=39,174,96
ForegroundVisited=127,140,141

[Colors:View]
BackgroundAlternate=49,54,59
BackgroundNormal=35,38,41
DecorationFocus=61,174,233
DecorationHover=61,174,233
ForegroundActive=61,174,233
ForegroundInactive=189,195,199
ForegroundLink=41,128,185
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=239,240,241
ForegroundPositive=39,174,96
ForegroundVisited=127,140,141

[Colors:Window]
BackgroundAlternate=77,77,77
BackgroundNormal=49,54,59
DecorationFocus=61,174,233
DecorationHover=61,174,233
ForegroundActive=61,174,233
ForegroundInactive=189,195,199
ForegroundLink=41,128,185
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=239,240,241
ForegroundPositive=39,174,96
ForegroundVisited=127,140,141

[DirSelect Dialog]
DirSelectDialog Size=640,480
History Items[$e]=...

[General]
ColorScheme=Breeze Dark
Name=Breeze Dark
XftAntialias=true
XftHintStyle=
XftSubPixel=none
shadeSortColumn=true
widgetStyle=Breeze

[Icons]
Theme=breeze-dark

[KDE]
ColorScheme=Breeze
LookAndFeelPackage=org.kde.breezedark.desktop
contrast=4
widgetStyle=Breeze

[KFileDialog Settings]
Automatically select filename extension=true
Breadcrumb Navigation=true
Decoration position=0
LocationCombo Completionmode=5
PathCombo Completionmode=5
Show Bookmarks=false
Show Full Path=false
Show Inline Previews=true
Show Preview=false
Show Speedbar=true
Show hidden files=false
Sort by=Name
Sort directories first=true
Sort reversed=false
Speedbar Width=107
View Style=Simple
listViewIconSize=0

[KShortcutsDialog Settings]
Dialog Size=600,480

[WM]
activeBackground=49,54,59
activeBlend=255,255,255
activeForeground=239,240,241
inactiveBackground=49,54,59
inactiveBlend=75,71,67
inactiveForeground=127,140,141
```

**Comment by eteran** [comment] 2020-01-13 16:12
OK, you're right, there are indeed no font entries in there :-).

I'll see what I can do to look into this.

**Comment by jahodb** [comment] 2020-01-14 09:23
I can confirm the same behaviour. My configuration:
SUSE Linux Enterprise Desktop 12 (x86_64)
VERSION = 12
PATCHLEVEL = 4
Plasma 5.12 (2018-03-23)

There was only one entry with the string "Regular" in my ~/.config/kdeglobals : 
toolBarFont=Noto Sans,10,-1,5,50,0,0,0,0,0,Regular

I removed the string and restarted, but it did not help. Du you have some other tips, thanks.

**Comment by jahodb** [comment] 2020-01-14 09:40
One comment more - list of fonts for them bold style works:
- B&H Lucida Typewriter
- Bitstream Vera Sans Mono
- DejaVu Sans Mono
- Symbol Neu

**Comment by eteran** [comment] 2020-01-14 13:59
Unfortunately, I'm not sure offhand, but I'm going to explore the issue a bit. It's odd that it works for some, but not others.

I was really hopeful that it was what I thought it was, but it seems that it's a separate bug :-(.

**Comment by eteran** [comment] 2020-02-05 14:54
This may be fixed in the lastest master/release (hard to say since I haven't reproduced the problem specifically). Please give things a try and let me know if it fixes the issue.

**Comment by jahodb** [comment] 2020-02-11 10:46
It seems to be much better - most of fonts work fine. According to my quick test the bold style does not work for: cursor.pcf, deccurs.pcf, decsess.pcf, Schumacher clean, Sony Fixed. Thanks.

**Comment by eteran** [comment] 2020-02-12 04:48
Awesome.

**Closed by eteran** 2020-02-12 04:48 UTC
