### ISSUE TITLE
text zooming work intermittently on Terminal font

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#289] opened 2021-01-18 05:12 UTC
Set font to Terminal font size 10 on Windows 10. Pressing Ctrl '+' or Ctrl '-' has no effects, font size stay unchanged. Other font families tested (Courier New, Consolas, Lucida Console, etc) appeared to be working fine.

Using commit 3d7f8caea9df299f72f040781fdec511bcee17b2

**Comment by eteran** [comment] 2021-01-18 15:32
I think the issue may be that the terminal font simply doesn't have many standard font sizes. (NG simply asks the system, "what sizes can I expect fonts to support in general) and uses those. In theory, we could ask on a per font basis what specific sizes it supports.

Perhaps that would be a better solution.

**Comment by anjohnson** [comment] 2021-01-18 16:56
> NG simply asks the system "what sizes can I expect fonts to support in general" and uses those.

I can see that approach causing problems, it might even be the cause of the issue I'm seeing in #274. I suspect the MacOS characters are not really an integer number of pixels wide when the OS renders them.

**Comment by eteran** [comment] 2021-01-19 00:41
Yea, I'll probably make it use per font sizes 👍

**Comment by tksoh** [comment] 2021-01-19 01:47
> Yea, I'll probably make it use per font sizes

Actually I am a little surprised it's not already so. I personally wouldn't bet on people conforming to the so-call standards ;-)

**Comment by eteran** [comment] 2021-01-19 04:39
Yea, perhaps it was optimistic to assume that all fonts implemented the "standard sizes"

**Comment by eteran** [comment] 2021-01-19 04:40
I can say, that regardless of the solution, "zooming" that particular font, or any font with very few sizes will continue to have this issue. There's not much we can do if the font literally isn't available at the needed sizes.

**Comment by tksoh** [comment] 2021-01-19 05:11
> "zooming" that particular font, or any font with very few sizes will continue to have this issue. 

I don't quite follow here. You mean you want to keep it this way, to have the sizes presented even if they are not actually there?

**Comment by tksoh** [comment] 2021-01-19 05:12
BTW, just a small thing I noticed, perhaps nedit should beep when we try to zoom beyond the smallest/largest font sizes.

**Comment by eteran** [comment] 2021-01-19 05:23
@tksoh I've considered the beep, but I wasn't sure if it would be annoying :-P.

Regarding the zoom.

No, I will do my best to present sensible size options for each font (PR incoming soon).

What I mean, is that there are some fonts that only have a few sizes (Specifically the bitmap fonts). So attempting to "zoom" them will just appear to not work. Like for me "Misc Fixed" only offers `5, 6, 7, 8, 10, 11, 14, 15` All of which are bordering on microscopic on my screen because they don't scale with HiDPI.

For this font, and others like it, we can try to set sizes outside of that range... but it won't do anything, they'll still remain small and to the user, it will just look like it isn't doing anything at all.

**Comment by eteran** [comment] 2021-01-19 05:25
I'm also seeing an issue where these bitmap fonts lie about their current size, making the "zoom" appear to get stuck (I set it to 14, and it reports back that it's at 15.. so next zoom out, I set it to 14 and it reports back 15 ... rinse repeat)

**Comment by eteran** [comment] 2021-01-19 05:56
@tksoh should be better in master (and yes, it should beep when you zoom too big or small for the font).

Just keep in mind that these bitmap fonts really don't play nice, so i can't (yet) promise perfection :-P.

Closing for now, please re-open if the problem isn't fixed.

**Closed by eteran** 2021-01-19 05:56 UTC

**Comment by grege2** [comment] 2021-01-19 22:04
Hi, I'm coming to this issue late. I may be displaying my ignorance here, but I had no idea that Ctrl +/-, or Cmd +/- on Mac, would directly change the font size. Is that a built-in feature of a Qt "TextWindow", or did you add it in @eteran ? It doesn't seem to be documented anywhere in nedit5 or nedit-ng doco. It's actually a great feature, worthy of highlighting in Nedit 6.0 release. You can quickly jump to a large size to focus on a tricky bit of text, maybe a nasty regex, and jump to a small size to see some code with very long lines. Etc. Of course Cmd +/- zooms lots of other stuff on Mac.

Just to add some tiny value here .. the changed font is nicely reflected in the nedit vars:

```
$font_name                Consolas,288,-1,5,50,0,0,0,0,0
$font_name_bold           Consolas,288,-1,5,50,0,0,0,0,0
$font_name_bold_italic    Consolas,288,-1,5,50,0,0,0,0,0
$font_name_italic         Consolas,288,-1,5,50,0,0,0,0,0
$max_font_width           158
$min_font_width           158
```

**Comment by eteran** [comment] 2021-01-19 22:05
Not Qt native, It's a feature I added . You can also Ctrl+Scroll!

**Comment by grege2** [comment] 2021-01-19 22:31
Holy crap, indeed you can. (Cmd-scroll for me). Outstanding. That would be near the top of Nedit 6.0 feature list for me !
(I think I may have been missing the point of some of these font-related issues lately .. "there's a nanopixel of some bold character shaved off .. Huh ?? who's ever going to notice that ?? I guess you'll notice it plenty when zoomed up. Ok, back to my granddaughter's alphabet blocks for me, they work really well, and you can spell stuff .. only one font ..
