### ISSUE TITLE
nc-ng does not open files

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#133] opened 2019-10-19 05:56 UTC
Opening a file with nc-ng command is not possible without -svrname option.
This command opens an Untitled window
nc-ng test
This command open the file
nc-ng -svrname myserver test

nedit-nc works with both commands.

Without svrname option nedit-nc also does not show any server name in the window title and nc-ng shows a 8 character string [b0e7d506].

**Comment by eteran** [comment] 2019-10-20 18:20
Are you sure this isn't a bug in nc-ng? In the configuration, there is an implicit server name, which is supposed to be used when none is specified.

If it's not a bug, Is there a compelling reason why one behavior is more desirable over the other?

**Comment by eteran** [comment] 2019-10-20 18:21
Not shorting the server name is in fact a bug it seems though!

**Comment by eteran** [comment] 2019-10-20 18:48
The "no server name" part should be fixed in latest

**Comment by eteran** [comment] 2020-02-05 04:54
This seems to be have been fixed incidentally. Please re-open if the problem persists.

**Closed by eteran** 2020-02-05 04:54 UTC
