### ISSUE TITLE
Windows Split Pane does not retain position

### ISSUE THREAD

**Issue by mmarxmeier** [eteran/nedit-ng#317] opened 2021-07-22 19:11 UTC
Splitting the window vertically should preferably open the new pane in the same position as nedit does.
Currently (2020.1) NG starts the new pane at the begining.

**Comment by eteran** [comment] 2021-07-23 14:15
Interesting. Does it have the same behavior when splitting horizontally? Or is it only an issue with the vertical split?

**Comment by eteran** [comment] 2021-07-24 18:15
@mmarxmeier just for clarification, there is a setting in the config.ini which lets you choose horizontal vs vertical splitting.

Also, we should be clear on terms. When you say "splitting the window vertically", do you mean that the split itself is up/down making the two panes side by side? Or that the panes themselves are arranged vertically? LOL.

I only ask because to me, a "vertical split" is the first option, but that's only available from the undocumented option described above.

Either way, I'll look into it and see if I can reproduce :-).

**Comment by grege2** [comment] 2021-07-25 04:19
Hi all, I tested this on Mac. I hadn't tried the vertical split before. So `nedit.splitHorizontally=true` in config.ini changes the split to be "horizontal", with a vertical divider. My nedit maintains the line numbers fine - the two panes start at the same line number. (Line numbers are also correct with the default split mode).

My version is built from the master download of 25jun21. Qt 5.15.2, Boost 1.76.0. Big Sur 11.5.  

Ciao.

**Comment by mmarxmeier** [comment] 2021-07-26 16:19
Thnank you for looking into this.

I can see the same behaviour, regardless if nedit.splitHorizontally set to true/false.
The current position is not retained in the new pane in either mode. 
I'm using the nedit-ng that comes with opensuse 15.3. It shows the following version info

nedit-ng version 2020.1

    Built on: Linux, x86_64, GCC 7.5.0
      With Qt: 5.9.7
   Running Qt: 5.12.7
       Locale: en-DE

If there was a change related to that funtionality i can build form the latest source.

**Comment by eteran** [comment] 2021-08-02 03:16
@mmarxmeier One last question :-)>>

It sounds like you're running the latest release, have you tried building master? I **think** i fixed this bug sometime a few months ago.

**Comment by eteran** [comment] 2021-11-10 23:44
I believe that this was resolved by the change that fixed https://github.com/eteran/nedit-ng/issues/239 in the master branch. Please reopen if the issue persists.

**Closed by eteran** 2021-11-10 23:44 UTC
