### ISSUE TITLE
text area does not get focus when open new tab or files

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#299] opened 2021-01-29 08:58 UTC
Using 5b11433df41980af1ff647e0d9a28c2a0fb12bc6 on Windows & Linux

When opening a new tab or open a file, NG does not place the focus in the text editor area. I need to explicitly click in the text editor area before I can edit or navigate around the file.

**Comment by eteran** [comment] 2021-01-29 15:05
Is this a new issue? I feel like I haven't experienced this anytime recently

**Comment by eteran** [comment] 2021-01-29 15:30
Hmm... it appears that it is!

**Comment by eteran** [comment] 2021-01-29 15:36
Interesting, appears to be related to a setting. When I clear out my config to defaults, it doesn't happen, even with master.

**Comment by eteran** [comment] 2021-01-29 15:52
@tksoh Darn, I made a small mistake. I didn't back up my config before clearing my settings and now I can't figure out which setting caused it.

Any chance you can send me a copy of your config? Whatever it is, it appears to be just in `config.ini`, so I don't need any macros or language modes.

**Comment by tksoh** [comment] 2021-01-30 01:23
I narrowed down to this setting:

> nedit.focusOnRaise=true

**Comment by eteran** [comment] 2021-01-30 01:27
aha, awesome, thanks! that actually makes sense. I'll see what I can do :-).

I expect that the issue is that I am telling it to focus the **document**, but that's the parent widget of the text area, and can technically have the focus on its own.

Should be a simple fix once I figure out the appropriate way to set the focus on what we want.

**Comment by eteran** [comment] 2021-01-30 01:32
Should be fixed in master now, thanks :-)

**Closed by eteran** 2021-01-30 01:32 UTC
