### ISSUE TITLE
ctrl-y does not work with absolute file names

### ISSUE THREAD

**Issue by mrbald** [eteran/nedit-ng#64] opened 2018-09-22 21:31 UTC
When I try to `ctrl-y` an absolute location `/home/bobah/...` it shows an error dialog "could not open `/home/bobah//home/bobah/...` ..."

**Comment by eteran** [comment] 2018-09-23 11:47
I believe this is a dupe of issue #61 , which has been fixed in master. Please re-open if the issue is reproducible in the master branch.

**Closed by eteran** 2018-09-23 11:47 UTC

**Comment by mrbald** [comment] 2018-09-25 19:11
In the master build `ctrl-y` works correctly indeed. Thanks @eteran
