### ISSUE TITLE
crash with commit 2d89f455

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#115] opened 2019-06-13 07:47 UTC
Here is stack trace report of a crash with commit 2d89f4553224e35a723f39aba5ba2025232950f9

Is this something you can use to figure out what goes wrong?

```
#0  0x00002ba83918936e in QObject::~QObject() () at /lib64/libQt5Core.so.5
#1  0x00000000004e72fb in DocumentWidget::<lambda()>::operator()(void) const (this=0xa627bf0, __in_chrg=<optimized out>) at /tmp/nedit-ng/src/DocumentWidget.cpp:63
#2  0x00000000004e72fb in DocumentWidget::<lambda()>::operator()(void) const (this=<optimized out>, __ptr=0xa627bf0)
    at /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:76
#3  0x00000000004e72fb in DocumentWidget::<lambda()>::operator()(void) const (__p=0xa627bf0, this=<optimized out>) at /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:347
#4  0x00000000004e72fb in DocumentWidget::<lambda()>::operator()(void) const (this=<optimized out>) at /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:283
#5  0x00000000004e72fb in DocumentWidget::<lambda()>::operator()(void) const (__closure=__closure@entry=0x7ffcfcc7f6f0) at /tmp/nedit-ng/src/DocumentWidget.cpp:4530
#6  0x00000000004ee83d in DocumentWidget::processFinished(int, QProcess::ExitStatus) (this=0xa645800, exitCode=9, exitStatus=<optimized out>)
    at /tmp/nedit-ng/GSL/include/gsl/gsl_util:74
#7  0x00002ba8391818b3 in QMetaObject::activate(QObject*, int, int, void**) () at /lib64/libQt5Core.so.5
#8  0x00002ba8390ea5af in QProcess::finished(int, QProcess::ExitStatus) () at /lib64/libQt5Core.so.5
#9  0x00002ba8390f1363 in QProcessPrivate::_q_processDied() () at /lib64/libQt5Core.so.5
#10 0x00002ba8390f5d87 in QProcessPrivate::waitForFinished(int) () at /lib64/libQt5Core.so.5
#11 0x00002ba8390eb032 in QProcess::waitForFinished(int) () at /lib64/libQt5Core.so.5
#12 0x00002ba8390eb6ca in QProcess::~QProcess() () at /lib64/libQt5Core.so.5
#13 0x00002ba8390eb769 in QProcess::~QProcess() () at /lib64/libQt5Core.so.5
#14 0x00002ba839182385 in QObjectPrivate::deleteChildren() () at /lib64/libQt5Core.so.5
#15 0x00002ba83857e312 in QWidget::~QWidget() () at /lib64/libQt5Widgets.so.5
#16 0x00000000004e8336 in DocumentWidget::~DocumentWidget() (this=0xa645800, __in_chrg=<optimized out>) at /tmp/nedit-ng/src/DocumentWidget.cpp:570
#17 0x00000000004e8369 in DocumentWidget::~DocumentWidget() (this=0xa645800, __in_chrg=<optimized out>) at /tmp/nedit-ng/src/DocumentWidget.cpp:587
#18 0x00002ba839182868 in QObject::event(QEvent*) () at /lib64/libQt5Core.so.5
#19 0x00002ba838582f7b in QWidget::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#20 0x00002ba8385447ec in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#21 0x00002ba83854be38 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#22 0x00002ba8391592e6 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#23 0x00002ba83915bc03 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt5Core.so.5
#24 0x00002ba8391a8113 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5Core.so.5
#25 0x00002ba83da58049 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#26 0x00002ba83da583a8 in g_main_context_iterate.isra.19 () at /lib64/libglib-2.0.so.0
#27 0x00002ba83da5845c in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#28 0x00002ba8391a7abc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#29 0x00002ba839157deb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#30 0x00002ba839160234 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#31 0x00000000004876e5 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /tmp/nedit-ng/src/nedit.cpp:124
```

**Comment by eteran** [comment] 2019-06-13 15:56
I'll see of it's something I can figure out.

**Comment by eteran** [comment] 2019-06-13 16:09
Looks like it's a crash in the cleanup after a shell command was being executed. Would it be possible for you to provide an example shell command that reproduces the problem?

**Comment by marilmanen** [comment] 2019-06-14 06:25
Unfortunately it did not happen right after a shell command so I'n not sure what the cause is. It happened after I was working on a different tool and activated the nedit window. One possible cause is read_file() with non-existing file name argument (I had a bug in my macro), but now that I have been trying to reproduce the issue, it does not cause a crash, so looks like this will be a mystery crash that we'll catch later:

**Comment by eteran** [comment] 2019-06-14 13:47
Very odd, had you used the shell command feature at all in that session? Looking at the call stack I see things like this:

    #6  0x00000000004ee83d in DocumentWidget::processFinished(int, QProcess::ExitStatus) (this=0xa645800, exitCode=9, exitStatus=<optimized out>)

and 
```
#8  0x00002ba8390ea5af in QProcess::finished(int, QProcess::ExitStatus) () at /lib64/libQt5Core.so.5
#9  0x00002ba8390f1363 in QProcessPrivate::_q_processDied() () at /lib64/libQt5Core.so.5
#10 0x00002ba8390f5d87 in QProcessPrivate::waitForFinished(int) () at /lib64/libQt5Core.so.5
#11 0x00002ba8390eb032 in QProcess::waitForFinished(int) () at /lib64/libQt5Core.so.5
#12 0x00002ba8390eb6ca in QProcess::~QProcess() () at /lib64/libQt5Core.so.5
#13 0x00002ba8390eb769 in QProcess::~QProcess() () at /lib64/libQt5Core.so.5
```
All of which indicate that the crash happened during the shutdown of the shell feature.

**Comment by marilmanen** [comment] 2019-06-15 05:53
It might be that I had used Shell/sort and Shell/number lines functions on that session.

**Comment by eteran** [comment] 2019-09-06 13:47
Closing since I am unable to replicate. But please do report any future crashes, ideally with a process to reproduce if you can.

**Closed by eteran** 2019-09-06 13:47 UTC
Labels: bug

**Comment by eteran** [comment] 2019-10-24 01:49
Diagnosed as the same as issue #130, which has been resolved!
