### ISSUE TITLE
nc-ng -svrname usage

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#102] opened 2019-05-21 18:23 UTC
There seems to be some issue with the -svrname option.

Here are the commands I use to get two tabs in a single NEdit with a given server name
nedit-nc -svrname test CMakeLists.txt
nedit-nc -svrname test CMakeSettings.json 

With similar commands nc-ng gives two separate Untitled windows.
nc-ng -svrname test CMakeLists.txt
nc-ng -svrname test CMakeSettings.json

**Comment by eteran** [comment] 2019-05-21 19:58
This may be a duplicate of another issue which we thought was resolved. I'll investigate!

Thanks for the report

**Comment by eteran** [comment] 2019-05-22 13:17
Well yea, I can reproduce this locally. I will fix this ASAP!

**Comment by eteran** [comment] 2019-05-22 13:35
Should be fixed in latest master

**Closed by eteran** 2019-05-22 13:35 UTC

**Comment by anjohnson** [comment] 2019-05-22 17:34
This fix seems to have resolved _part_ of my issue (now #98) that I was getting extra Untitled windows.
