### ISSUE TITLE
nc-ng window activation

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#103] opened 2019-05-24 12:45 UTC
When opening file and the file is already open in a server window with same name, the server window is not activated automatically. Activation happens only if the existing window is minimized.
Server window does the tab change correctly, so the only issue seems to be that the window activation is missing.

**Comment by markmr** [comment] 2019-05-24 17:02
Yes, I have encountered the same issue. Since I was already preparing a bug report, here is my text:

Title: Background (partially hidden) Nedit-NG window does not get focus when opening a file via nc-ng

Steps to reproduce:

0) Close any open Nedit-NG windows

1) Start a terminal window

2) ~# touch File-1 File-2

3) ~# nc-ng File-1
     A new NEdit-NG window is created and has focus. File-1 is opened in the first tab.

4) Change to the terminal window (NEdit-NG looses focus) an enter
   ~#  nc-ng File-2
     File-2 is opened in NEdit-NG in a second tab, but NEdit-NG does not get focus. 

Maybe this is the same problem legacy Nedit had before "EWMH raise support" patch. See https://sourceforge.net/p/nedit/patches/172/

Markus

**Comment by eteran** [comment] 2019-05-28 14:25
I'll definitely look into this!

**Comment by tksoh** [comment] 2020-12-08 06:49
On Linux Mint, I noticed if I set 'nedit.focusOnRaise=true', it will raise the raise/activate the window. But this is not what the flag is meant for in the old nedit:

> This setting determines whether new text windows and text windows that are raised, should also request the input focus. Conventionally, it is the task of the window manager to decide on which window gets the input focus. Therefore, NEdit-ng's default behaviour is not to request the input focus explicitly.

nedit-ng seems to be working the other way round somehow, raising the window that has the focus, rather than giving focus the raised window.

@eteran maybe some issue with the implementation? Or I miss-interpreted it?

BTW, Qt's activateWindow has no effect on Windows per their doc. Perhaps that's the reason it doesn't jump to nedit-ng even if I set that flag to true.

**Comment by eteran** [comment] 2020-12-21 23:26
@tksoh I think you let me to the solution (I hope)! The raise should be outside the `if(focus)` because this function should raise the window regardless of the `nedit.focusOnRaise` setting. That setting should effect whether or not we attempt to set the focus to the window as well! (I think)...

**Comment by eteran** [comment] 2020-12-21 23:26
@marilmanen @markmr Could you guys checkout the PR and see if it helps this issue?

https://github.com/eteran/nedit-ng/pull/215

**Comment by eteran** [comment] 2020-12-24 07:47
This issue was auto-closed because it was linked to a PR that was merged. It **may** be fixed, please let me know if it is still a persistent issue.

**Comment by sjtringali** [comment] 2020-12-26 18:15
This code exists for two reasons, IIRC. One is to work around window managers that don't follow the focus-on-raise hints for rop-level windows correctly. 

A second reason was really annoying; if you had a dialog window that was already open (e.g., Find) but is modeless, then ^F should absolutely raise AND set focus to it.

**Comment by eteran** [comment] 2020-12-26 18:46
> This code exists for two reasons, IIRC. One is to work around window managers that don't follow the focus-on-raise hints for top-level windows correctly (focus on raise).
> 
> A second reason was really annoying - if you had a dialog window that was already open (e.g., Find) but is modeless, then ^F should absolutely raise AND set focus to it.
> 

Makes sense. I think I have finally squared away how this function should work and I THINK this issue should be fixed in master now.

@marilmanen please confirm when you get a chance 🙂

**Comment by marilmanen** [comment] 2020-12-27 05:34
Yep, no more issue with window activation.

**Closed** 2020-12-27 22:13 UTC
