### ISSUE TITLE
Problem loading autoload.nm in nedit-ng from Mac build

### ISSUE THREAD

**Issue by grege2** [eteran/nedit-ng#176] opened 2020-11-14 01:08 UTC
Hi all,
On Mac my old autoload.nm fails to load, and nedit-ng fails with a Segmentation Fault.
I've narrowed it down to a couple of lines in autoload.nm:
```
$line_marking = $empty_array
$line_marking["\n"] = $empty_array
```
The autoload loads fine if I comment those out. These are a couple of inits for some "rangeset" functions which I must have played with years ago, can't remember anything about it, and I never use this code.

I'll append the full autoload.nm file. Any thoughts appreciated, but I can easily live without those functions. I've forgotten the little I used to know about Nedit's macro language so haven't debugged it further just yet, but I probably will, I'd like to re-learn the language.

Cheers, GE.

[autoload.nm.failing.txt](https://github.com/eteran/nedit-ng/files/5539957/autoload.nm.failing.txt)

**Comment by eteran** [comment] 2020-11-14 19:47
I believe this is a duplicate of #171 which has been fixed in the master branch.

**Closed by eteran** 2020-11-14 19:47 UTC

**Comment by grege2** [comment] 2020-11-14 19:54
Ah, yes that looks likely. Apologies, I didn't search for the problem in previous issues. Thanks.

**Comment by eteran** [comment] 2020-11-16 00:26
No worries at all! Just happy to have you as a new user :-) So please, file issues as you encounter them (hopefully they will few!)
