### ISSUE TITLE
NEdit does not get the correct path to a file when used to open a file in Windows Explorer

### ISSUE THREAD

**Issue by lester96** [eteran/nedit-ng#160] opened 2020-03-14 00:05 UTC
When I right click on a file in windows explorer and and do an "open with" to use nedit, nedit tries to open a file using a path of "C:/Windows/system32/"prefixing the full path to the file. This obviously doesn't work, and opens a blank window with a popup error message. The path it tried to open is also lost, so that you have to browse the final location. This was a problem with the prior Windows version also, so it is not a new issue.

**Comment by eteran** [comment] 2020-03-14 00:33
Interesting, I'll check it out.

**Comment by eteran** [comment] 2020-03-25 03:17
I **think** I know what the problem is. My guess is that nedit-ng is testing for an "absolute" path by checking if the path starts with a `"/"`. On windows, it doesn't, so it appends the current working directory of the application, which is `"C:/Windows/System32/".

I'll confirm this and try to get a patch in there for ya.

**Comment by eteran** [comment] 2020-03-25 03:58
I almost had it right, it was a quirk with path parsing regarding `"\"` and `"/"`. Should be fixed now though!

**Closed by eteran** 2020-03-25 03:58 UTC
