### ISSUE TITLE
open and focus_window

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#222] opened 2020-12-23 06:13 UTC
I wanted to use a macro to open file and set it to Read Only mode, so I used macro
```
open("/tmp/foobar")
focus_window("/tmp/foobar")
set_locked(1)
```
Result is not what I expected i.e. the file from which the macro was executed becomes locked and the /tmp/foobar is not locked. With old NEdit I get the lock to the /tmp/foobar file.

**Comment by eteran** [comment] 2020-12-23 06:30
Interesting indeed. The `focus_window` code does try to set the "macro focus" to the new target. It's probably something silly. Nice subtle find! I'll check it out.

**Comment by eteran** [comment] 2020-12-23 06:41
OK, I see the issue. There are two functions in nedit's macro implementation. `MacroRunDocument` and `MacroFocusDocument`.

They return the document that either executed the macro or is the focus (set by `focus_window`) respectively. The `set_locked` is using `MacroRunDocument`.

However, it is using it via a template that is used in MANY places.

So I need to do an audit to make sure that ALL of them are supposed to operate on the focused document :-(.

**Comment by eteran** [comment] 2020-12-23 07:01
This PR **should** fix it. Please test before I merge it in :-)

https://github.com/eteran/nedit-ng/pull/223

**Comment by marilmanen** [comment] 2020-12-23 07:44
I changed my nedit version and now my macro is working ok. I should have now some free time, so I'll play with nedit-ng for couple days and see if I can find something new or some way to reproduce existing issues.

**Comment by eteran** [comment] 2020-12-23 07:48
Awesome, going to merge this PR then !

**Comment by marilmanen** [comment] 2020-12-24 07:06
There seems to be some additional issue with the focus_window as it does not change the active window to a detached window if the file is already open. The correct tab in the detached window is changed, so only active window change (and raise) seems to be missing. I tested also with old NEdit and it changes the active window.

**Comment by eteran** [comment] 2020-12-24 07:22
Interesting, I was under the impression that `focus_window` only changed the focus of what the macro would effect. I'll have to look at the classic NEdit's code more... Reopening.

**Comment by eteran** [comment] 2020-12-24 07:32
@marilmanen OK, I know what's up. Believe it or not, we are BOTH right ;-)

`focus_window` does NOT in NEdit-5 activate the window, and it doesn't even change to the tab... but `open` DOES!

So `focus_window` in NG is working correctly, but `open` needs a small fix to make it also activate the window.

**Comment by eteran** [comment] 2020-12-24 07:33
BTW, I tested this by having a macro with ONLY a focus command, and in classic NEdit, it didn't switch tabs, it didn't activate the window. But if I preceded that `focus_window` with an `open` it works as you described.

**Comment by eteran** [comment] 2020-12-24 07:44
LOL, already had a PR to address this.

However, I can say that it only works EXACTLY like you say if you also have `focusOnRaise` set in your config.ini file.

I'll merge the PR in, since it seems to be the correct behavior.

**Comment by eteran** [comment] 2020-12-24 07:55
OK, after reviewing classic NEdit's code, I think **now** master should have the effect that you expect.

Closing this issue again, please re-open if the problem is not solved :-).

**Closed by eteran** 2020-12-24 07:55 UTC
