### ISSUE TITLE
macro replace_in_string not handling regex correctly

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#97] opened 2019-05-13 09:22 UTC
Here is an example of replacing start of string with text and it does not work as expected. Similar issue seems to be also with line ending regex with "$"

```
text="bar"
text=replace_in_string(text, "^", "foo", "regex", "copy")
dialog(text, "OK")
```

**Comment by eteran** [comment] 2019-05-15 02:02
I'll look into this

Thanks!

**Comment by eteran** [comment] 2019-05-16 16:54
Fixed in master. Should address all regex related issues for commands such as:

`replace_in_string`, `split`, `search_string`, etc...

**Comment by marilmanen** [comment] 2019-05-20 09:14
Looks like there is still issue with line end matching. Here is a macro for adding quotes to given message and the trailing quote is missing.

message = string_dialog("Give message")
message = replace_in_string(message, "^", "\"", "regex", "copy")
dialog(message, "OK")
message = replace_in_string(message, "$", "\"", "regex", "copy")
dialog(message, "OK")

**Comment by eteran** [comment] 2019-05-20 13:49
OK, I'll look at it some more!

**Comment by eteran** [comment] 2019-05-20 13:52
This macro has a syntax error, the `"""` needs to be `"\""` (assuming you wanted to place a quote)

**Comment by eteran** [comment] 2019-05-20 14:58
OK, The second half of the issue is slightly more complex...

Basically, nedit-ng is failing to match `$` when it happens to be the very last character in the string being checked. I imagine this is a result of my refactoring things to not require null termination.

I'll try to get this fixed ASAP, but it may be more of a challenge than the one line fix the first half got.

**Comment by eteran** [comment] 2019-05-22 15:11
Interesting. This is a case of specifically the regex `"$"` (end of line, but nothing else) failing to match the end of the buffer.

For example, given the string "test", "t$" will match, ut "$" won't!

This is certainly a bug that needs to be fixed, I'll try to work it out ASAP.

Thanks again for the report.

**Comment by eteran** [comment] 2019-10-16 00:16
I think this has been fixed. Please re-open if the problem persists.

**Closed by eteran** 2019-10-16 00:16 UTC
Labels: bug, major
