### ISSUE TITLE
tag file very slow to load

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#188] opened 2020-11-25 08:54 UTC
Using tag file generated by ctags on the recent copy of nedit-ng repo, the classic nedit would load and find the definition almost instantaneously, while nedit-ng took about 6-7 seconds. All files involved have been opened before pressing Ctrl-D.

Some info on the ctag data:
> nedit-ng$ ctags -R
nedit-ng$ wc tags
  19206  163329 2779645 tags

Similar issue is observed on both Linux (Mint 19.3) and Windows 10, built with Qt 5.9.x.

**Comment by eteran** [comment] 2020-12-04 05:49
Can you attach the tag file you used? I'm sure that I'd be happy to optimize the crap out of it :-P

**Comment by tksoh** [comment] 2020-12-05 01:55
Tag file attached. 

BTW, I took a stab at it to improve the load time (considering you might be busy with other stuffs, and also as an exercise to learn more about nedit-ng ;-) -- it's the least disruptive way I can find so far. You can find the changes on my branch, along with a couple of fixes on the handling of tag files:

[git branch: _ctags-matters_](https://github.com/tksoh/nedit-ng/commits/ctags-matters)

[ctags.gz](https://github.com/eteran/nedit-ng/files/5646281/ctags.gz)

**Comment by tksoh** [comment] 2020-12-05 02:02
In any case, I am getting a feeling that the tag file feature is not being used as much in these 'modern' days. Naturally I'd like to see it working better, i.e. faster, since I still use it quite a lot, especially coupling with my own tag-stack feature. So I can understand if this is not a high priority.

**Comment by eteran** [comment] 2020-12-05 02:40
Awesome, I'll take a look.

Admittedly, the ctags stuff is not a feature I ever really used much if at all. But I am a big advocate for making things fast ;-).

One note on your fixes, if you look at the master branch, there are two other spots where a similar fix was needed. But I prefer to place that code in an `#ifdef` because `QDir::listSeparator` didn't exist until Qt 5.6.

Now... After this next release, I do plan to bump the minimum requirements to C++17 and Qt 5.9. But for now, my CI chain insists on Qt 5.5 being supported :-)

**Comment by tksoh** [comment] 2020-12-05 02:54
Yeah, on QDir::listSeparator, I just found out too it was only introduced in Qt 5.6, and I was about to ask you what the minimum version of Qt should nedit-ng support. If you still intend to keep it below 5.6 (the wiki call for Qt => 5.9 on windows), then we will have to put in the code to mimic the functionality of QDir::listSeparator -- this probably would just eliminate the need for QDir::listSeparator all together. I will take a look at it.

Off topic: since github doesn't support mailing, do you see the need to host a mailing list somewhere somehow, so the discussion like this can take place? I'm not sure if the issue tracker is the right place.

**Comment by tksoh** [comment] 2020-12-05 02:59
BTW, anything in C++ 17 that are compelling for the upgrade? I welcome all improvement naturally, but these language support can get tricky on older systems, across various compiler suites or platforms (linux, windows, mac, etc).

**Comment by eteran** [comment] 2020-12-05 03:02
I have been considering a discord or similar :-).

Regarding C++17. It's mostly the ability to have slightly cleaner code and easier to get correct idioms. It would eliminate the need to depend on boost and `string_view` would be a built-in library so I wouldn't need to include my own implementation.

So it would be a pretty meaningful improvement for **my** end of things. Users wouldn't see any real difference at all.

**Comment by tksoh** [comment] 2020-12-05 03:18
I have used discord supported in other projects. Personally, it can get quite 'noisy' and hard to keep up with the discussion on specific topics of interests. Coming from the old nedit team, it'd not be a surprise I still very much prefer the old mode of communication ;-) IMHO, mailing lists or forums are still the better platforms for discussion on technical topics. In any case, it's your call :)

Getting rid of boost, or any external dependencies for that matter, is a great idea ^^

**Comment by tksoh** [comment] 2020-12-05 05:23
FYI, I just pushed another change to my branch to take care of the issue on QDir::listSeparator. Tested on Windows 10 and Linux Mint. Let me know if you have any comment/questions.

**Comment by eteran** [comment] 2020-12-06 02:37
I like your solution to make it operate on windows correctly even with < Qt 5.6 !

**Comment by eteran** [comment] 2020-12-08 02:53
@tksoh BTW, I almost forgot, I actually setup a gitter for this project, feel free to message me there, and if you happen to catch me at the right time, it can be much more real time:

https://gitter.im/nedit-ng/Lobby

(Link also via badge in README on the top)

**Comment by tksoh** [comment] 2020-12-08 02:57
@eteran cool! I'll check it out.

**Comment by eteran** [comment] 2020-12-08 11:32
@tksoh can you elaborate on how you test ctags loading speed? When I open nedit-ng, and choose "File -> Load Tags File" and choose the ctags you provided (after gunziping), it loads more or less instantly for me.

Are you opening any source files and searching for anything in particular to trigger the slowness?

**Comment by tksoh** [comment] 2020-12-08 12:04
Did you try to lookup for a tag?

Loading the tag files doesn't actually load the tags, the tags are actually loaded on the first time we invoke Find Definition.

**Comment by tksoh** [comment] 2020-12-08 12:08
BTW, to 'amplify' the load time, I'd make two identical copies of ctags and load them, just to make it a little more obvious

**Comment by eteran** [comment] 2020-12-08 12:50
@tksoh so I don't use this feature too much :-P. So if you could give specific instructions that would help.

I did try to search for a definition, but it always said not found, so I must be forgetting exactly how it works, LOL.

**Comment by eteran** [comment] 2020-12-08 13:00
OK, loading and searching for "DocumentWidget" via highlight + "Ctrl+D" takes 2-3 seconds for me on a release build. (Just checking, you didn't choose a debug build did you? It should default to "Release with Debug Info" which is basically `-O2 -g`

**Comment by tksoh** [comment] 2020-12-08 13:02
No problem. To look for a tag, I simply load, say mainwindow.cpp file in the nedit-ng source directory, select one of the class names, then press ctrl D, and it should open the file where the class is defined and highlight the class name. I presume the ctags file is copied into the root of the source directory and loaded from there.

In any case, even if it says not found, it should mean that it already loaded the tag files. Any idea how long it took between pressing ctrl D and the not found dialog?

**Comment by tksoh** [comment] 2020-12-08 13:10
You beat me to my reply ;-)

You are right. I was using the debug build, which is significantly longer than your two second, and very inconsistent too. I will try out the release build later.

But even at 2-3 seconds, that still quite slow compared to classic nedit compiled with -O0 -g. To be fair, motif is a lot lighter than Qt, but we probably should it's performance as close as perceivably possible.

**Comment by eteran** [comment] 2020-12-08 13:12
Yea, it's consistently taking about 2 seconds for me. I agree it should be faster. I don't think it's a Qt vs Motif thing since this is a data-driven operation. I think it's probably a QFile vs FILE thing. Possibly due to Unicode conversions. I think it could be MUCH faster :-D. I'll see what I can do, because a file this size SHOULD be basically instant.

Though this did reveal a repeatable way to reproduce a different bug :-P.

When I use this to open a new document the cursor blinks SUPER fast and uses like 50% of my CPU... I've seen it like ONCE before, so having a good way to reproduce is useful.

**Comment by tksoh** [comment] 2020-12-08 13:13
Perhaps let me try out the release builds before we proceed further. 

Just curious, did you try out my patch to see if the performance is better?

**Comment by eteran** [comment] 2020-12-08 13:17
not yet, but I plan to later today

**Comment by tksoh** [comment] 2020-12-08 13:22
Also, I did try to manually benchmark the QFile read, and it only to about 100ms+ on my system. The tag file size is only about 2MB after all.

I still can't get CPU profiling working in Qt Creator,  so I can't pinpoint where the bottlenecks really are for now. I actually used the timer to measure elapsed time in the tag loading loop.

**Comment by eteran** [comment] 2020-12-08 13:32
OK, so it's not FileIO, it must be all the string operations and related allocations. If I were willing to commit to a MUCH more recent version of Qt, I'd switch a bunch of stuff to be QStringView's which would be likely much more performant.

But... I think we can figure this one out even so!

**Comment by tksoh** [comment] 2020-12-09 08:57
FYI. I tested with release builds today. On my Windows 10, the master branch took about 4-5s to load ctags of nedit-ng source, vs about 1s with my branch. The debug build of master took a whopping 16-18s (O.O), not sure what the compiler did with it (I suspect it's linking to the debug version of Qt also, as I can't believe the compiler can optimize the nedit-ng code to this extend). 

The performance comparison feels similar on my Linux Mint box, so I didn't bother to clock them.

BTW, I found this page comparing the performance between QString and std::string, maybe there's something to it:

https://cukic.co/2014/10/03/api-design-and-impact-on-the-performance-qt-vs-stl-example/

Optimization is great fun ;-)

**Comment by eteran** [comment] 2020-12-10 05:33
nice, if you are satisfied that the code is correct, it sounds like a definite improvement. So feel free to open a PR for it!

As for Debug/Release.. honestly, my experience is that measuring the performance of debug code is not really reflective of how the code will perform at all when doing an optimized build. Modern compilers are bordering on magic these days ;-).

**Comment by eteran** [comment] 2020-12-10 05:39
Oh... I see something simple that may be a HUGE difference in speed.

If the `scanCTagsLine` function is part of the call chain, it is currently very slow. Mainly because it is constructing a `QRegaExp` object (the older API!) every time!

The better way to do it, since it's a static string, is to use a static `QRegularExpression` object that is static and thus compiled once.

That alone should be a big speed up! I'll work on a simple patch for it :-D

**Comment by eteran** [comment] 2020-12-10 05:48
OK, pushed an update to master for the `QRegularExpression` bit. Can you check to see if that made a meaningful difference on your end?

**Comment by tksoh** [comment] 2020-12-10 06:03
I actually did something very similar with QRegularExpression, but didn't see a very significant improvement. Let me try it again.

**Comment by tksoh** [comment] 2020-12-10 06:05
I moved regex outside the function instead of make it static const -- thought about that though but didn't think it matter that much. Let's see..

**Comment by tksoh** [comment] 2020-12-10 06:28
Your change seems to take about a second off my earlier result, that's about 25% improve. Nice work. Maybe Qt like you better ;-)

And applying your change to my branch, I'd say it's a lot more tolerable at least for my usage. I'd open a PR. We can continue the optimization as we go along.

**Comment by eteran** [comment] 2020-12-10 15:57
Ha! Maybe you didn't make it a static variable so it was getting created every time it was called?

Either way, closing this issue, please reopen if performance of this feature remains an issue (or becomes one again)

**Closed by eteran** 2020-12-10 15:57 UTC
Labels: performance

**Comment by tksoh** [comment] 2020-12-11 03:23
@eteran on the topic of mailing list, github just prompted me to try their new discussion feature (still in beta though), but it looks like something useful. Have you tried that?

**Comment by eteran** [comment] 2020-12-11 03:24
I haven't! I'll have to check it out for sure. 👍

**Comment by eteran** [comment] 2020-12-15 15:34
@tksoh

Just a heads up, I have enabled discussions for this project :-)

https://github.com/eteran/nedit-ng/discussions

See you there!
