### ISSUE TITLE
close tab button issue on Linux Mint

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#256] opened 2021-01-08 08:45 UTC
On Linux with Qt 5.9.5, somehow the close tab button appears as a kind of 'window' button, rather than the usual [X] on Windows with Qt 5.9.9 (foreground in the attached screenshot, which is also same as nedit-5). 

![2021-01-08 16_39_15-Untitled](https://user-images.githubusercontent.com/494222/103993559-c11eca00-51d0-11eb-86ac-e23513b81698.jpg)

**Comment by eteran** [comment] 2021-01-08 15:42
So that's a theming issue. Some desktops use that icon as the "close-tab" button. I am considering embedding a better choice like I have for other icons into the nedit binary since I agree, that icon is terrible.

**Comment by eteran** [comment] 2021-01-08 15:44
This is what it looks like with KDE, much better :-P


![image](https://user-images.githubusercontent.com/571477/104034116-76845a00-519e-11eb-9591-fc3acb2ad4db.png)

**Comment by eteran** [comment] 2021-01-08 22:49
OK, this is a weird one... I already **DO** have it built into the theme. I'll get to the bottom of it though. It looks like it is for some reason ignoring my theme stuff... just for that function.

**Comment by eteran** [comment] 2021-01-08 23:24
It gets even weirder, it is for some reason, using the "window" icon from the theme as the close-tab button. No idea why, LOL

**Comment by eteran** [comment] 2021-01-08 23:54
@tksoh 

OP, possibly fixed in master (is in the VM that I ran to replicate). There seems to be a bug in Qt that it is using the icon for "window" when in the close it looks like it's trying to pull from "window-close". But I've worked around it by renaming the theme entry to "whole-window" which seems to avoid this weird name collision.

Please re-open if the problem is not fixed.

**Closed by eteran** 2021-01-08 23:54 UTC
