### ISSUE TITLE
crash with 4586bf54

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#116] opened 2019-06-14 11:19 UTC
This time crash happened while I was running shell command through xterm_csh macro.
The command had stopped and the xterm was just waiting for the `<enter>`, so no action going on at the moment of the crash.

Here is the stack trace. Let me know if there's something more I can do, but please note that I have practically no experience in SW debugging.

```
#0  0x000000000058bc73 in gap_buffer<char, std::char_traits<char> >::operator[](long) const (this=this@entry=0x391be70, n=n@entry=1072693247)
    at /tmp/nedit-ng/src/gap_buffer.h:132
#1  0x000000000058c299 in BasicTextBuffer<char, std::char_traits<char> >::searchBackward(BasicTextCursor<int>, char) const (this=this@entry=0x391be60, startPos=..., searchChar=searchChar@entry=10 '\n') at /tmp/nedit-ng/src/TextBuffer.tcc:1143
#2  0x000000000058c2e9 in BasicTextBuffer<char, std::char_traits<char> >::BufStartOfLine(BasicTextCursor<int>) const (this=this@entry=0x391be60, pos=...)
    at /tmp/nedit-ng/src/TextBuffer.tcc:756
#3  0x000000000058ef64 in BasicTextBuffer<char, std::char_traits<char> >::BufGetTextInRectEx(BasicTextCursor<int>, BasicTextCursor<int>, long, long) const (this=0x391be60, start=..., end=..., rectStart=4294967297, rectEnd=20903376) at /tmp/nedit-ng/src/TextBuffer.tcc:466
#4  0x000000000058f302 in BasicTextBuffer<char, std::char_traits<char> >::getSelectionTextEx(BasicTextBuffer<char, std::char_traits<char> >::Selection const*) const (this=<optimized out>, sel=<optimized out>) at /tmp/nedit-ng/src/TextBuffer.tcc:1165
#5  0x000000000058f360 in BasicTextBuffer<char, std::char_traits<char> >::BufGetSelectionTextEx() const (this=<optimized out>)
    at /tmp/nedit-ng/src/TextBuffer.tcc:607
#6  0x000000000058a3d1 in TextAreaMimeData::retrieveData(QString const&, QVariant::Type) const (this=0x4956a80, mimeType=..., type=QVariant::ByteArray)
    at /tmp/nedit-ng/src/TextAreaMimeData.cpp:23
#7  0x00002b9296907ca6 in QMimeDataPrivate::retrieveTypedData(QString const&, QVariant::Type) const () at /lib64/libQt5Core.so.5
#8  0x00002b9296908ebd in QMimeData::data(QString const&) const () at /lib64/libQt5Core.so.5
#9  0x00002b92962edc76 in QInternalMimeData::renderDataHelper(QString const&, QMimeData const*) () at /lib64/libQt5Gui.so.5
#10 0x00002b929ec6724f in QXcbMime::mimeDataForAtom(QXcbConnection*, unsigned int, QMimeData*, QByteArray*, unsigned int*, int*) () at /lib64/libQt5XcbQpa.so.5
#11 0x00002b929ec57685 in QXcbClipboard::sendSelection(QMimeData*, unsigned int, unsigned int, unsigned int) () at /lib64/libQt5XcbQpa.so.5
#12 0x00002b929ec57e15 in QXcbClipboard::handleSelectionRequest(xcb_selection_request_event_t*) () at /lib64/libQt5XcbQpa.so.5
#13 0x00002b929ec5ef6e in QXcbConnection::handleXcbEvent(xcb_generic_event_t*) () at /lib64/libQt5XcbQpa.so.5
#14 0x00002b929ec60dee in QXcbConnection::processXcbEvents() () at /lib64/libQt5XcbQpa.so.5
#15 0x00002b929690e81e in QObject::event(QEvent*) () at /lib64/libQt5Core.so.5
#16 0x00002b9295cd07ec in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#17 0x00002b9295cd7e38 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#18 0x00002b92968e52e6 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#19 0x00002b92968e7c03 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt5Core.so.5
#20 0x00002b9296934113 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5Core.so.5
#21 0x00002b929b1e4049 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#22 0x00002b929b1e43a8 in g_main_context_iterate.isra.19 () at /lib64/libglib-2.0.so.0
#23 0x00002b929b1e445c in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#24 0x00002b9296933abc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#25 0x00002b92968e3deb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#26 0x00002b92968ec234 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#27 0x00000000004875e5 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /tmp/nedit-ng/src/nedit.cpp:124
```

**Comment by eteran** [comment] 2019-06-14 13:58
Hmm, this is a different crash! This has to do with the middle click copy/paste mechanism. Somehow it referenced the buffer out of bounds... but I don't really see how that's possible since there is a guard around the code :-/.

**Comment by marilmanen** [comment] 2019-06-15 04:41
I'm using Linux with NoMachine running in Windows, so maybe there's something special in the copy/paste handling which is not considered by the guard. At least the copy/paste functionality between NX and Windows has always been a real challenge with NoMachine. Even with latest version the copy/paste between NX and Windows does not always work and I hate random functionality. During the crash I was working on the windows side, so maybe NX did some copy/paste related actions on the Linux side.

**Comment by eteran** [comment] 2019-06-15 14:39
Oh you're doing some wierd Linux on windows thing? Nedit-ng can also be built on windows...

**Comment by marilmanen** [comment] 2019-06-16 05:36
My personal computer and all work related tasks are done in Linux, but there has always been some company policy that forces using Windows as the primary OS. Hopefully my next employer allows pure Linux environment.

**Comment by eteran** [comment] 2019-09-06 13:47
Closing since I am unable to replicate. But please do report any future crashes, ideally with a process to reproduce if you can.

**Closed by eteran** 2019-09-06 13:47 UTC

**Comment by eteran** [comment] 2019-10-24 01:48
Diagnosed as the same as issue #135 . That issue will be used to track this.
