### ISSUE TITLE
crash sequence for commit af2fb602

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#130] opened 2019-09-07 08:33 UTC
Here is a sequence that seems to causes a crash.
Start nedit-ng in build directory
File/Open CMakeCache.txt and install_manifest.txt (select both files)
(Shell/Execute Command does not work in install_manifest.txt tab, so something is not right here)
Repeat detaching install_manifest.txt tab, closing or moving CMakeCache.txt tab and File/Open for both files and try to execute Shell/Execute command (cancel if pop-up comes). Within couple iterations at least I get a crash.

**Comment by eteran** [comment] 2019-10-07 16:06
These spurious crashes **might** be fixed in the latest master. I found a way to simplify some memory management and there was at least some code involving macros which could at least in theory access a pointer after it was destroyed. I think this should be fixed now.

Please re-open if the problem persists (I was unfortunately unable to reproduce this issue).

**Comment by eteran** [comment] 2019-10-09 01:54
Interesting...

OK, I'll re-open, and see if I can replicate :-(

**Comment by eteran** [comment] 2019-10-09 01:59
OK, I **think** I have an idea of what the issue is!

Basically it has to do with static variables living past things that they reference (I this case a static variable for a dialog, which references a `MainWindow`). When the MainWindow is switched/destroyed, and **another** one is created, then boom.

Should be able to fix this reasonably soon if it is what I think it is!

**Comment by eteran** [comment] 2019-10-09 02:39
If this issue was what I think it was, then I hope this commit will fix the issue for you!

**Closed by eteran** 2019-10-09 02:39 UTC

**Comment by marilmanen** [comment] 2019-10-09 16:17
I'm not able to reproduce the issue anymore :-) 

Issue with "Shell/Execute Command does not work in install_manifest.txt tab" was at my mistake as I didn't check that the file had no write permission and thus shell command is not supported (just like in the old NEdit).

**Comment by eteran** [comment] 2019-10-09 18:29
Nice!

I think that this was the core of all the crashes you had experienced.

Glad to hear that we finally got to the bottom of it 👍.

Thanks for your reporting and patience as I figured this one out.
